name: anki
favicon: null
layout_spectrum: 0.50446
typography_spectrum: 0.94559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6a90b2'
    - '#89cbbe'
    - '#cc4754'
    - '#3b2726'
    - '#f4edcc'
  brandStrength: 0.5
  lightness: 0.9103089389391243
  saturation: 0.5
  rhythmicContrast: 0.3244105076882988
purpose: []
